-- Generated by scripts/listings_to_sql.py from tenants/demo/. Idempotent.
insert into public.tenants (slug, name) values ('demo', 'LeaseLine demo')
on conflict (slug) do nothing;

insert into public.listings (tenant_id, slug, status, title, street, unit, city, province, postal_code, neighbourhood, property_type, rent_monthly, beds, baths, sqft, available_now, available_on, pets, laundry, cooling, heating, parking_spots, parking_type, utilities_included, tenant_pays, amenities, highlights, outdoor, storage, transit, description, mls_number)
values ((select id from public.tenants where slug = 'demo'), 'gladstone-920-1', 'published', '920 Gladstone Ave, Unit 1', '920 Gladstone Ave', '1', 'Ottawa', 'ON', 'K1R 6Y4', 'Little Italy', 'Duplex (ground floor)', 2695, 2, 1, '700', true, null, 'Pet friendly', 'In-unit', 'None', 'Forced air (natural gas)', 2, 'driveway', array['heat', 'water']::text[], array['hydro']::text[], '{}', array['Fully renovated; no one has lived in it since', 'Bright', 'Large private backyard, rare this close to downtown', 'Two driveway parking spots']::text[], 'Large private backyard', 'Large unfinished basement', 'About a 30-second walk to Corso Italia O-Train station', '## About this home
A bright two-bedroom, one-bathroom unit on the ground floor of a fully renovated duplex in
Little Italy, one of Ottawa''s most walkable neighbourhoods, minutes from downtown. It''s brand
new since the renovation, so the next tenant is the first to live in it. It''s about a
30-second walk to the Corso Italia O-Train station, near Gladstone and Preston.

## Good fit for
- Someone who needs parking for two cars: there are two driveway spots.
- Pet owners: the unit is pet friendly.
- Anyone who wants outdoor space: a large private backyard, rare this close to downtown.
- People who want two bedrooms, or a bedroom plus an office.
- Transit commuters, with the O-Train right around the corner.

## Good to know
- Rent is $2,695 a month. Heat and water are included; the tenant pays hydro.
- In-unit laundry.
- There''s no air conditioning. Heating is forced air, natural gas.
- A large unfinished basement gives lots of storage.
- Available immediately.', 'X13689140')
on conflict (tenant_id, slug) do nothing;

insert into public.listings (tenant_id, slug, status, title, street, unit, city, province, postal_code, neighbourhood, property_type, rent_monthly, beds, baths, sqft, available_now, available_on, pets, laundry, cooling, heating, parking_spots, parking_type, utilities_included, tenant_pays, amenities, highlights, outdoor, storage, transit, description, mls_number)
values ((select id from public.tenants where slug = 'demo'), 'icon-805-carling-1105', 'published', 'The Icon, 805 Carling Ave, Unit 1105', '805 Carling Ave', '1105', 'Ottawa', 'ON', 'K1S 5W9', 'Dow''s Lake / Little Italy', 'Condo apartment (11th floor)', 2400, 1, 1, '600–699', false, null, 'Allowed with restrictions (details to be confirmed)', 'In-suite', 'Central air conditioning', 'Forced air (natural gas)', 1, 'underground', array['heat', 'water']::text[], array['hydro', 'internet']::text[], array['24/7 concierge', 'Indoor pool', 'Sauna', 'Fitness centre', 'Yoga studio', 'Theatre room', 'Party rooms', 'Resident lounge', 'Outdoor terraces with BBQs']::text[], array['South-facing, direct view of Dow''s Lake and the canal', 'In the Claridge Icon, Ottawa''s tallest building', 'Floor-to-ceiling windows, hardwood floors, quartz counters, walk-in glass shower', 'All utilities included except hydro and internet']::text[], 'Balcony', 'Storage locker', 'Steps to the O-Train', '## About this home
A one-bedroom, one-bathroom condo on the 11th floor of the Claridge Icon, Ottawa''s tallest
building, at Carling and Preston. It faces south with a direct view of Dow''s Lake and the canal,
through floor-to-ceiling windows. Inside: hardwood floors, quartz counters, a walk-in glass
shower, and a balcony.

## Good fit for
- Someone who wants a view and a full-service building: 24/7 concierge, indoor pool, sauna,
  gym, yoga studio, theatre room, party rooms, resident lounge, and terraces with BBQs.
- Someone with one car: one underground parking spot, plus a storage locker.
- Anyone who wants air conditioning (central air).
- People who like being steps from Dow''s Lake, the canal pathways, Little Italy''s restaurants
  and cafés, and the O-Train, with easy access to Carleton, the Civic Hospital, and downtown.

## Good to know
- Rent is $2,400 a month. All utilities are included except hydro and internet.
- In-suite laundry.
- Pets are allowed with building restrictions; the specifics need to be confirmed with the
  leasing team.
- The availability date hasn''t been confirmed yet.', 'X13839592')
on conflict (tenant_id, slug) do nothing;

