"""Generate supabase/seed.sql from the repo's tenant + listing files (one-time migration of the
demo data into Supabase; also used to seed a local Supabase).

    uv run python scripts/listings_to_sql.py demo > supabase/seed.sql
"""

import sys
from datetime import date
from pathlib import Path

from leaseline.loader import validate_tenant
from leaseline.models import TBD, Parking


def lit(value: object) -> str:
    if value is None or value == TBD:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return f"{value:g}" if isinstance(value, float) else str(value)
    if isinstance(value, date):
        return f"'{value.isoformat()}'"
    if isinstance(value, list):
        return "array[" + ", ".join(lit(v) for v in value) + "]::text[]" if value else "'{}'"
    return "'" + str(value).replace("'", "''") + "'"


def main(slug: str) -> None:
    report = validate_tenant(Path("tenants") / slug)
    if not report.ok or report.tenant is None:
        sys.exit("\n".join(report.errors))
    print(f"-- Generated by scripts/listings_to_sql.py from tenants/{slug}/. Idempotent.")
    print(
        f"insert into public.tenants (slug, name) values ({lit(slug)}, {lit('LeaseLine demo')})\n"
        "on conflict (slug) do nothing;\n"
    )
    for listing in report.listings:
        parking = listing.parking if isinstance(listing.parking, Parking) else None
        cols = {
            "tenant_id": f"(select id from public.tenants where slug = {lit(slug)})",
            "slug": lit(listing.id),
            "status": "'published'",
            "title": lit(listing.title),
            "street": lit(listing.address.street),
            "unit": lit(listing.address.unit),
            "city": lit(listing.address.city),
            "province": lit(listing.address.province),
            "postal_code": lit(listing.address.postal_code),
            "neighbourhood": lit(listing.neighbourhood),
            "property_type": lit(listing.property_type),
            "rent_monthly": lit(listing.rent_monthly),
            "beds": lit(listing.beds),
            "baths": lit(listing.baths),
            "sqft": lit(None if listing.sqft == TBD else str(listing.sqft)),
            "available_now": lit(listing.available == "immediately"),
            "available_on": lit(listing.available if isinstance(listing.available, date) else None),
            "pets": lit(listing.pets),
            "laundry": lit(listing.laundry),
            "cooling": lit(listing.cooling),
            "heating": lit(listing.heating),
            "parking_spots": lit(parking.spots if parking else None),
            "parking_type": lit(parking.type if parking else None),
            "utilities_included": lit(listing.utilities_included),
            "tenant_pays": lit(listing.tenant_pays),
            "amenities": lit(listing.amenities),
            "highlights": lit(listing.highlights),
            "outdoor": lit(listing.outdoor),
            "storage": lit(listing.storage),
            "transit": lit(listing.transit),
            "description": lit(listing.body),
            "mls_number": lit(listing.source.mls_number if listing.source else None),
        }
        print(f"insert into public.listings ({', '.join(cols)})")
        print(f"values ({', '.join(cols.values())})")
        print("on conflict (tenant_id, slug) do nothing;\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "demo")
